spring.application.name: outbox-kafka-consumer-service

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/outbox-db
    username: appuser
    password: appassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    topic: outbox
    bootstrap-server: localhost:9092
    consumer:
      client-id: outbox
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-rest: earliest
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: com.patterns.dtos
            value:
              default:
                type: com.patterns.dtos.UserEventsDTO
            add:
              type:
                headers: false
    producer:
      client-id: outbox
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false