spring.application.name: outbox-kafka-producer-service

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/outbox-db
    username: appuser
    password: appassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    topic: outbox
    bootstrap-server: localhost:9092
    producer:
      client-id: outbox
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: rg.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false

debezium:
  name: engine
  connector-class: io.debezium.connector.mysql.MySqlConnector
  bootstrap-servers: localhost:9092
  database:
    hostname: localhost
    port: 3306
    user: root
    password: rootpassword
    server-id: 85744
    server-name: mysql-server-1
    include-list: outbox-db
  table:
    include-list: outbox-db.user_events
  offset:
    storage: org.apache.kafka.connect.storage.FileOffsetBackingStore
    storage-file-filename: offsets.dat
    flush-interval-ms: 60000
  schema-history:
    internal: io.debezium.storage.file.history.FileSchemaHistory
    internal-file-filename: schema-history.dat
  topic:
    prefix: outbox